### ISSUE TITLE
Horus x10s

### ISSUE THREAD

**Issue by effysh** [teckel12/LuaTelemetry#192]
Hi
wonder if there is any future support for the Horus x10s Tx with this project?

**Comment by teckel12** [comment]
@effysh See #55. It's planned, but there doesn't seem to be much interest as I believe your the first Horus owner to request it. 

Horus would be implemented as a view just for Horus transmitters. This view would incorporate the multiple views available on Taranis.

The issues are theee-fold. First, I don't have a Horus transmitter so I don't completely understand how it would even work (I don't even know the procedure to setup a script on the Horus simulator). Secondly, as I don't have a Horus, testing can only be done in the simulator, and without  a good simulation environment I can't even begin to test. Third, and most importantly, Horus users need to step up and be willing to help, with creating a simulation build environment, method of setting up a script, testing code, or even better submitting pull requests with written/tested code.

As it is now, there's only a plan. What's needed is the Horus community to help, which is why I've flagged #55 as "help wanted".   I can't even start till I have a simulation environment to build on.

**Comment by teckel12** [comment]
Duplicate #55

**Comment by fchansa** [comment]
Request from a second Horus owner :-)

**Comment by fmartinezo** [comment]
Request for a possible third horus owner :-)

**Comment by teckel12** [comment]
@fmartinezo Request all you want, I can't write what I dont have nor understand. Issue #55 is tagged as help needed I believe.

**Comment by teckel12** [comment]
Closed because this is a duplicate request.
