### ISSUE TITLE
I can not restore widget  color as you say in the 7 point

### ISSUE THREAD

**Issue by fmartinezo** [teckel12/LuaTelemetry#234]
I can not restore widget  color as you say in the 7 point
may you put several photos on how to do it?

**Comment by teckel12** [comment]
@fmartinezo Be sure you're using v1.5.1, there was an issue in v1.5.0 which was corrected in v1.5.1.

Changing widget settings is done the same for all widgets. When selecting a widget, long-press enter and select widget settings, then set the widget options as you like.

Are you having a hard time finding how to change widget settings? Or, are you setting them but they don't seem to work?

**Comment by fmartinezo** [comment]
@teckel12 I am using a screen with 3 widgets. Two for the flight time and another with the model's photo.
The version is 1.5.1 and what I can not find is how to change the options of the widget. That's why I was asking for the photos of how and where to do it

**Comment by teckel12** [comment]
@fmartinezo I'm not able to provide that (not at a computer). When you setup a widget, just long-press `enter` to bring up a menu (this is where you select a widget, or set the settings for a widget).

To be clear, this has nothing to do with Lua Telemetry, it's how the Horus works. There's probably a YouTube video on how to setup widgets on the Horus and how to set the "widget settings". Maybe a Google search on: `horus widget options settings`?

**Comment by teckel12** [comment]
@fmartinezo. Maybe this will help? 

https://raw.githubusercontent.com/yaapu/FrskyTelemetryScript/master/HORUS/IMAGES/horus_wstep12.png

https://raw.githubusercontent.com/yaapu/FrskyTelemetryScript/master/HORUS/IMAGES/horus_wstep17.png

https://raw.githubusercontent.com/yaapu/FrskyTelemetryScript/master/HORUS/IMAGES/horus_wstep19.png

**Comment by fmartinezo** [comment]
The problem is that the widgets that I bring out in the first screen do not have any configuration. However I have found a way to do it and it is reloading the base theme (I use the one that comes out flying a model airplane, there is another blue one and one with tbs). But this is not functional at all so I'll leave it like this.

**Comment by teckel12** [comment]
@fmartinezo You don't set the settings for other widgets, you change the widget settings for Lua Telemetry. Each widget can have settings (some have none). The `Restore`, `Text` and `Warning` widget settings which I'm referring to are for Lua Telemetry.

Basically, the way Horus widgets work is if a widget changes a color (like Lua Telemetry does), it changes the color for all widgets.  Because Lua Telemetry changes the text and warning color, other widgets may not look correct after installing Lua Telemetry. As a solution, you simply tell Lua Telemetry what colors you want to restore to. These are the widget settings options I'm referring to.

I hope that makes sense. If not, do some research on how widgets work on the Horus as I've tried to explain it in as much detail as I can.

**Comment by fmartinezo** [comment]
Ok understand. Now is working fine.
