### ISSUE TITLE
PID settings

### ISSUE THREAD

**Issue by laurentopia** [teckel12/LuaTelemetry#267]
### Is your feature request related to a problem? Please describe.
BF lua have PID settings, iNav does not so OSD pid is required.

### Describe the solution you'd like
Adding PID in lua, also integrating the VTX lua script would be great.

### Describe alternatives you've considered
OSD is possible but requires extra channels

**Comment by teckel12** [comment]
@laurentopia 

Incorporating VTx may be possible, but duplicated on issue #157.  It's scheduled to be researched, but no promises due to limited documentation.

PID adjustment is out of scope.  Lua Telemetry is not designed to be a substitute for BF's lua script.  BF lua script can mostly be used with INAV.  I would suggest using the BF lua script to adjust your PIDs as that won't be incorporated into a telemetry script designed to give telemetry feedback.
