### ISSUE TITLE
Why are some configuration settings options disabled?

### ISSUE THREAD

**Issue by 87040109qq** [teckel12/LuaTelemetry#277]
Speed sensor,View Mode and GPS HDOP View can not be set ! Even after I got " GPS OK" voice prompt !
here is my set:
hours10(2.2.3)+D4R II (Frsky Telemetry)+INAV2.0.1 +Lua Telemetry 1.6.2 
How can I change those parameters ?

**Comment by 87040109qq** [comment]
What kind of conditions would make those three parameters addressable?

**Comment by teckel12** [comment]
@87040109qq You can't set options which don't apply to your situation.  For example, `View Mode` can't be set because you're using Horus which combines all views into one view.  On Taranis, you must switch between (for example) pilot and map view because you can't see both at the same time.  On Horus, you can see all views all the time, so that option is disabled.

Same is true with the rest of the options.  `Speed Sensor` is only an option if you have a pitot air speed sensor.  You don't have that so the option is disabled.

`GPS HDOP View` is also disabled because you're using Horus which shows all options so there's no reason for the option to exist.

Please see the Wiki for more information on the configuration menu options: 

https://github.com/iNavFlight/LuaTelemetry/wiki/Configuration-Settings

Also, please notice the note on the Wiki page which states the following:

> Options without selections have either been disabled by another option setting or are not available on your transmitter or telemetry protocol

**Comment by teckel12** [comment]
> @87040109qq What kind of conditions would make those three parameters addressable?

If you had a pitot tube speed sensor and a Taranis transmitter those options would be available.

**Comment by 87040109qq** [comment]
Thank you for your detailed reply!
