### ISSUE TITLE
Telemetry via CRSF

### ISSUE THREAD

**Issue by putimir** [teckel12/LuaTelemetry#38]
Hi, the betaflight-tx-lua-revised scripts now offer telemetry / configuration of the BF via CRSF link without the need for an additional s.port wire and with that, UART or Softserial, as I understand. 

Will these scripts work with iNav and if (probably not), is it possible at the moment, to port these to iNav?

Setups with GPS&Mag/Compass on F$ boards are REALLY scarce :)

**Comment by teckel12** [comment]
@putimir I'm working on an INAV branch to control PIDs and VTX via SmartPort telemetry. CRSF is a totally different type of telemetry which has nothing to do with SmartPort. Some get confused because they're using a Taranis receiver with a CRSF module. But they share nothing else in common having to do with telemetry. 

Basically, if your asking about CRSF telemetry, this is the wrong place, I don't have CRSF nor is this script at all compatible.
